version: '3'

services:

  front:
    image: imobiliario:front
    build: './front'
    depends_on:
      - 'back'
    ports:
      - '80:3000'

  back:
    image: imobiliario:back
    build: './back'
