version: '3'

services:

  www:
    image: tmvdl/projects:imobiliario
    build: './src/www'
    volumes:
      - './src/www:/app'
    ports:
      - '80:3000'
  
  api:
    image: imobiliario:api
    hostname: api
    build: './src/api'
    restart: always
    ports:
      - '8080:80'
    volumes:
      - './src/api:/app'
    depends_on:
      - 'adslist'
  
  adslist:
    image: imobiliario:adslist
    hostname: adslist
    build: './src/adslist'
    restart: always
    volumes:
      - './src/adslist:/app'
      - './src/main:/main'
      - './data:/data'
