name: AWS Lightsail

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:
      - name: Instance name
        id: instance
        run: echo "instancename=instance-$( date +%Y%m%d%H%M%S )" >> $GITHUB_OUTPUT

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Create instances in AWS Lightsail
        run: aws lightsail create-instances --instance-names ${{ steps.instance.outputs.instancename }} --availability-zone ${{ secrets.AWS_DEFAULT_REGION }}a --blueprint-id "ubuntu_20_04" --bundle-id "micro_1_0"

      - name: Get instance address by AWS Lightsail
        id: public_ip
        run: echo "public_ip=$( aws lightsail get-instance --instance-name ${{ steps.instance.outputs.instancename }} | jq ".instance.publicIpAddress" | sed -e 's/"//ig' )" >> $GITHUB_OUTPUT

      - name: Set instance private key
        run: |
          echo $( aws lightsail download-default-key-pair | jq ".privateKeyBase64" | sed -e 's/"//ig' ) | sed -e 's/\\n/\n/ig' >> key-pair.pem
          sudo chmod 400 key-pair.pem

      - name: List file in instance
        run: ls -la

      - name: Sleep 60sec
        run: sleep 60

      - name: List file in instance
        run: echo yes | ssh -i key-pair.pem ubuntu@${{ steps.public_ip.outputs.public_ip }} ls -la

