name: AWS Lightsail

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'

jobs:
  aws:
    using: docker
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run Dockerfile
        image: Dockerfile

