name: AWS Lightsail

on:
  workflow_dispatch:

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install JQ
        env:
          # AWS_REGION: us-east-1
          # AWS_ZONE: us-east-1a
          # INSTANCE_NAME: instance-${{ github.run_id }}
          KEY_PAIR_NAME: key-pair-${{ github.run_id }} 
        run: sudo apt install -y jq

      - name: Create key pair in Lightsail 
        env:
          KEY_PAIR_NAME: key-pair-${{ github.run_id }} 
        run: aws lightsail create-key-pair --key-pair-name $KEY_PAIR_NAME | jq ".privateKeyBase64" > ./key-pair.pem

      - name: List files 
        run: ls -la

