name: AWS Lightsail

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
  workflow_call:
    outputs:
      keypairname:
        description: "Name of key pair"
        value: keypairname-$( date +'%Y%m%d%H%M%S' )

jobs:

  aws:
    runs-on: ubuntu-latest
    outputs:
      keypairname: ${{ on.workflow_call.outputs.firstword.value	 }}
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Creating a key pair in AWS Lightsail
        run: aws lightsail create-key-pair --key-pair-name ${{ outputs.keypairname }} 

      - name: Listing key pairs in AWS Lightsail
        run: aws lightsail get-key-pairs

      - name: Getting key pairs in AWS Lightsail
        run: aws lightsail get-key-pair --key-pair-name ${{ outputs.keypairname }} 

      - name: Deleting a key pair in AWS Lightsail
        run: aws lightsail delete-key-pair --key-pair-name ${{ outputs.keypairname }} 
