name: AWS Lightsail

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Getting key pairs in AWS Lightsail
        runs: bash ./aws.sh lightsail get-key-pairs

