name: AWS Lightsail

on:
  workflow_dispatch:

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create key pair in Lightsail 
        run: aws lightsail create-key-pair --key-pair-name key-pair-${{ github.run_id }}

      - name: List key pairs in Lightsail 
        run: aws lightsail get-key-pairs

      - name: Get key pair in Lightsail 
        run: aws lightsail get-key-pair --key-pair-name key-pair-${{ github.run_id }}

      - name: Delete key pair in Lightsail 
        run: aws lightsail delete-key-pair --key-pair-name key-pair-${{ github.run_id }}
